# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-23 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_feedback', '0004_auto_20191218_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'permissions': [('view_feedback', 'Can view feedback')]},
        ),
    ]
