# Generated by Django 2.0.5 on 2018-05-09 05:47

from django.db import migrations


# create associated user profile instance for each existing user
def forwards(apps, schema_editor):
    user_model = apps.get_model('ndx_auth.NdxUser')
    userprofile_model = apps.get_model('ndx_auth.UserProfile')
    users = user_model.objects.all().prefetch_related('user_profile')

    for user in users:
        if not hasattr(user, 'user_profile'):
            u = userprofile_model.objects.create(user=user)
            u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0002_userprofile'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
