# Generated by Django 2.0.5 on 2018-05-10 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0003_auto_20180509_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the organisation. Necessary field.', max_length=60, unique=True)),
                ('address_line_1', models.CharField(help_text="The first line of the organisation's address.", max_length=60, null=True)),
                ('address_line_2', models.CharField(help_text="The second line of the organisation's address.", max_length=60, null=True)),
                ('address_line_3', models.CharField(help_text="The third line of the organisation's address.", max_length=60, null=True)),
                ('post_code', models.CharField(help_text="The organisation's postcode.", max_length=30, null=True)),
                ('state', models.CharField(help_text="The organisation's postcode.", max_length=30, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('manager', models.ForeignKey(help_text='The assigned manager of this organisation. Necessary field.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_organisation', models.ForeignKey(help_text='This field represents the parents organisation of this organisation, if assigned.', blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_organisations', to='ndx_auth.Organisation')),
            ],
        ),
        migrations.AddField(
            model_name='ndxuser',
            name='organisation',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='ndx_auth.Organisation'),
        ),
    ]
