# Generated by Django 2.0.5 on 2018-05-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0004_auto_20180510_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ndxuser',
            options={'permissions': (('view_ndxuser', 'can view all users'), ('view_all_orgs', 'can view all organisations'), ('view_org_users', 'can view own organisation users'), ('change_ndxuser_password', "can change a user's password"))},
        ),
    ]
