# Generated by Django 2.0.5 on 2018-05-17 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0004_auto_20180514_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='address_line_3',
        ),
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.TextField(default='', help_text='The full address, e.g. street, house number, city, etc.', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='manager',
            field=models.ForeignKey(help_text='The assigned manager of this organisation. Required.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(help_text='The name of the organisation. Required.', max_length=60, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='parent_organisation',
            field=models.ForeignKey(blank=True, help_text='The parent organisation of this organisation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_organisations', to='ndx_auth.Organisation', verbose_name='Parent organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='post_code',
            field=models.CharField(default='', max_length=30, verbose_name='Post code'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='state',
            field=models.CharField(default='', max_length=30, verbose_name='State'),
        ),
    ]
