# Generated by Django 2.0.5 on 2018-05-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0005_auto_20180517_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'permissions': (('change_own_organisation', 'Change the organisation the user is in.'),)},
        ),
    ]
