# Generated by Django 2.0.5 on 2018-05-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0009_auto_20180520_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ndxuser',
            options={'permissions': (('view_ndxuser', 'can view all users'), ('view_all_orgs', 'can view all organisations'), ('change_ndxuser_password', "can change a user's password"))},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'permissions': (('change_own_organisation', 'Change the organisation the user is in.'), ('view_organisation_user', "View the organisation's users."))},
        ),
    ]
