# Generated by Django 2.0.5 on 2018-05-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0010_auto_20180520_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'permissions': (('change_own_organisation', 'Change the organisation the user is in.'), ('view_organisation_user', "View the organisation's users."), ('add_organisation_manager', 'Create managers in the organisation.'), ('add_organisation_user', 'Create users in the organisation.'))},
        ),
    ]
