# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0013_auto_20180613_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ndxuser',
            options={'permissions': [('view_ndxuser', 'ndx_auth.view_ndxuser'), ('view_all_orgs', 'ndx_auth.view_all_orgs'), ('change_ndxuser_password', 'ndx_auth.change_ndxuser_password')]},
        ),
    ]
