# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_eula', '0001_initial'),
        ('ndx_auth', '0014_auto_20180628_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='eula_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ndx_eula.Eula', verbose_name='EULA accepted'),
        ),
    ]
