# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-29 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0017_auto_20190617_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndxuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email address already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
