# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-25 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0018_auto_20190829_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndxuser',
            name='feedback_emails',
            field=models.BooleanField(default=False, help_text='Indicates whether this user should receive emails notifying them feedback has been submitted.', verbose_name='Receives feedback emails'),
        ),
    ]
