# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-31 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0019_ndxuser_feedback_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ndxuser',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_all_orgs', 'ndx_auth.view_all_orgs'), ('change_ndxuser_password', 'ndx_auth.change_ndxuser_password'), ('edit_all_users', 'ndx_auth.edit_all_users'), ('view_all_users', 'ndx_auth.view_all_users'), ('view_user_data', 'ndx_auth.view_user_data'), ('change_feedback_emails', 'ndx_auth.change_feedback_emails'), ('view_ndxuser', 'view user'))},
        ),
    ]
