# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-31 14:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ndx_auth_source.models.ndx_user


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_auth', '0020_auto_20200131_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndxuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email address already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), ndx_auth_source.models.ndx_user.custom_validate_email], verbose_name='email address'),
        ),
    ]
