# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=127, verbose_name='Lot number')),
                ('valid_from', models.DateField(default=datetime.date.today, verbose_name='Manufacture date')),
                ('expires', models.DateField(help_text='The date after which this batch will no longer be valid.')),
                ('is_active', models.BooleanField(help_text='If not set, this Eula will not be shown to users.')),
                ('curve_type', models.CharField(choices=[('2', 'quadratic')], default='2', max_length=1)),
            ],
            options={
                'ordering': ('-valid_from',),
                'get_latest_by': 'valid_from',
            },
        ),
        migrations.CreateModel(
            name='QuadraticCurveParameters',
            fields=[
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quadratic_curve_parameters', serialize=False, to='ndx_batch.Batch')),
                ('a', models.FloatField(verbose_name='2nd degree coefficient')),
                ('b', models.FloatField(verbose_name='1st degree coefficient')),
                ('c', models.FloatField(verbose_name='Constant offset')),
            ],
        ),
    ]
