# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_batch', '0002_auto_20170531_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(help_text='If not set, this Batch will never be available to users.'),
        ),
    ]
