# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_batch', '0003_auto_20171214_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='assay_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Assay type'),
        ),
    ]
