# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_batch', '0004_batch_assay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='comments',
            field=models.TextField(default='', verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='batch',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Units'),
        ),
    ]
