# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-18 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_batch', '0005_auto_20191204_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
