# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-18 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_batch', '0006_auto_20191218_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='assay_type',
            field=models.CharField(max_length=64, verbose_name='Assay type'),
        ),
    ]
