# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_batch', '0007_auto_20191218_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='unit',
            field=models.CharField(max_length=64, verbose_name='Units'),
        ),
    ]
