# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Only the latest EULA is shown to users. Future dates possible.')),
                ('is_active', models.BooleanField(help_text='If not set, this Eula will not be shown to users.')),
            ],
            options={
                'ordering': ('-valid_from',),
                'get_latest_by': 'valid_from',
            },
        ),
        migrations.CreateModel(
            name='EulaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(help_text='For example: en, de, pt_BR', max_length=5, verbose_name='Language code')),
                ('eula_file', models.FileField(blank=True, null=True, upload_to='eula')),
                ('eula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eula_files', to='ndx_eula.Eula')),
            ],
        ),
    ]
