# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-31 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import ndx_eula.models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_eula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eulafile',
            name='locale',
            field=models.CharField(help_text='For example: en, de, pt-BR', max_length=5, validators=[ndx_eula.models.validate_language_code], verbose_name='Language code'),
        ),
    ]
