# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import ndx_eula.models


class Migration(migrations.Migration):

    dependencies = [
        ('ndx_eula', '0002_auto_20200131_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eulafile',
            name='eula_file',
            field=models.FileField(blank=True, null=True, upload_to='eula', validators=[
                ndx_eula.models.validate_eula_file_size,
                ndx_eula.models.validate_eula_file_type,
                ]),
        ),
    ]
